dataset:
  raw: 
    train: /content/drive/MyDrive/CaNhanHuynhNgan/Research_Space/ViWikiTableQA/2.Models/dataset/qa_train.csv
    dev: /content/drive/MyDrive/CaNhanHuynhNgan/Research_Space/ViWikiTableQA/2.Models/dataset/qa_dev.csv
    test: /content/drive/MyDrive/CaNhanHuynhNgan/Research_Space/ViWikiTableQA/2.Models/dataset/qa_test.csv
  preprocessed:
    train: /content/drive/MyDrive/CaNhanHuynhNgan/Research_Space/ViWikiTableQA/2.Models/easy/processed_data/train.csv
    dev: /content/drive/MyDrive/CaNhanHuynhNgan/Research_Space/ViWikiTableQA/2.Models/easy/processed_data/dev.csv
    test: /content/drive/MyDrive/CaNhanHuynhNgan/Research_Space/ViWikiTableQA/2.Models/easy/processed_data/test.csv

tokenizer: 
  padding: max_length
  truncation: True
  return_tensors: pt
  max_length: 
    input: 1024
    label: 32

train:
  checkpoint_dir: /content/
  bs: 4
  num_epochs: 100
  lr: 0.00002
  ealry_stopping_patience: 5

