dataset:
  raw: 
    train: ...
    dev: ...
    test: ...
  preprocessed:
    train: /content/OpenViTabQA_Experiments/vit5/src/data/train.csv
    dev: /content/OpenViTabQA_Experiments/vit5/src/data/dev.csv
    test: /content/OpenViTabQA_Experiments/vit5/src/data/test.csv

tokenizer: 
  padding: max_length
  truncation: True
  return_tensors: pt
  max_length: 
    input: 1024
    label: 32

train:
  checkpoint_dir: /content/drive/MyDrive/tableqa/checkpoint
  bs: 4
  num_epochs: 100
  lr: 0.00002
  early_stopping_patience: 5

pretrained_name: VietAI/vit5-large
predicted_path: ... # where to save the predicted file
