dataset:
  raw: 
    train: ...
    dev: ...
    test: ...
  preprocessed:
    train: /content/drive/MyDrive/tableqa/train.csv
    dev: /content/drive/MyDrive/tableqa/dev.csv
    test: /content/drive/MyDrive/tableqa/test.csv

tokenizer: 
  padding: max_length
  truncation: True
  return_tensors: pt
  max_length: 
    input: 768
    label: 16

train:
  checkpoint_dir: /content/drive/MyDrive/tableqa/checkpoint
  bs: 8
  num_epochs: 100
  lr: 0.00002
  ealry_stopping_patience: 5

