dataset:
  test: /content/drive/MyDrive/Projects/DS204/dataset/test.csv
  train: /content/drive/MyDrive/Projects/DS204/dataset/train.csv
  val: /content/drive/MyDrive/Projects/DS204/dataset/valid.csv

train: 
  checkpoint: /content/drive/MyDrive/Projects/DS204/models/Tapas/checkpoints/best_model.pt
  learning_rate: 0.00002
  train_bs: 8
  val_bs: 4
  num_epochs: 100

