dataset:
  raw: 
    train: /src/data/train.csv
    dev: /src/data/dev.csv
    test: /src/data/test.csv
  preprocessed:
    train: /src/data/preprocessed/train.csv
    dev: /src/data/preprocessed/dev.csv
    test: /src/data/preprocessed/test.csv

tokenizer: 
  padding: max_length
  truncation: True
  return_tensors: pt
  max_length: 
    input: 1024
    label: 32

train:
  checkpoint_dir: /content/drive/MyDrive/tableqa/checkpoint
  bs: 1
  num_epochs: 100
  lr: 0.00002
  early_stopping_patience: 1
  accumulation_steps: 4
  warmup_ratio: 0.03


pretrained_name: VietAI/vit5-base
predicted_path: ... # where to save the predicted file